services:
  redis:
    restart: always
    image: redis:latest
  db:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=knotify_webserver_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=knotify_webserver_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  celery:
    restart: always
    build:
      context: .
    command: celery -A knotify_webserver worker -l INFO
    depends_on:
      - db
      - redis
      - web
  web:
    restart: always
    build: .
    volumes:
      - .:/home/knotify_webserver
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

volumes:
  postgres_data: