services:
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    volumes:
    - ./knotify_webserver/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  db:
    container_name: db
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=knotify_webserver_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=knotify_webserver_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django:
    container_name: django
    restart: always
    build: .
    command: /home/knotify_webserver/docker-entrypoint.sh
    volumes:
      - .:/home/knotify_webserver
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - knotify
    environment:
      - DJANGO_SETTINGS_MODULE=knotify_webserver.settings
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.delete_expired_users.schedule: "@daily"
      ofelia.job-exec.delete_expired_users.command: "python3 manage.py delete_expired_users"
  knotify:
    container_name: knotify
    restart: always
    build:
      context: ./knotify/
    command: celery -A tasks worker -l INFO --max-tasks-per-child=1
    depends_on:
      - redis
  ofelia:
    container_name: ofelia
    restart: always
    image: mcuadros/ofelia:latest
    depends_on:
      - django
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  postgres_data:
