services:
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    networks:
      - backend
  db:
    container_name: db
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
  django:
    container_name: django
    restart: always
    build: .
    command: /home/knotify_webserver/docker-entrypoint.sh
    volumes:
      - .:/home/knotify_webserver
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - knotify
    env_file:
      .env
    networks:
      - frontend
      - backend
  knotify:
    container_name: knotify
    restart: always
    build:
      context: ./knotify/
    command: celery -A tasks worker -l INFO --max-tasks-per-child=1
    depends_on:
      - redis
    networks:
      - frontend
      - backend
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./static:/home/static
      - ./uwsgi_socket/:/home/uwsgi_socket/
    depends_on:
      - django
    networks:
      - frontend
volumes:
  postgres_data:
networks:
  frontend:
  backend:
