# Generated by Django 4.0.3 on 2022-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('ON', 'Ongoing'), ('FA', 'Failed'), ('CO', 'Completed')], default='ON', max_length=2),
        ),
    ]
